### PR TITLE
 replace stylelint-rule-tester with stylelint-test-rule-tape

### LINKED ISSUE #20: stylelint-rule-tester Should Be A devDependency
Because `stylelint-rule-tester` is a regular dependency, it gets installed every time you use the plugin. Besides the extra used space and bandwidth, the version used here has some warnings, so it adds a bit of visual clutter to any project using this plugin.

Thanks for the plugin!

### PR DESCRIPTION
**Pull request by stukalin**
Fix #20.

npm warns about deprecation. This fix uses the recommended library and also updates other packages to their latest versions.

@sh-waqar if you could merge this PR and release a new version that would be just nice

### CODE REVIEW

**Comment by sh-waqar** [comment]
@stukalin - thanks for the PR, I will review and release a new version. I haven't got time lately to update the library and I am not using it as well. Would you like to become the maintainer for this project?

**Comment by stukalin** [comment]
@sh-waqar done. As for the project maintaining... Well, you could add me as a mantainer. Maybe I'd have a look from time to time

**Comment by sh-waqar** [comment]
@stukalin - Thanks 🙇 all looks good. I will update the npm package and add you as maintainer for the project.

**Comment by sh-waqar** [comment]
Welcome

**Pull request merged**
