### PR TITLE
eliminate dependency vulnerabilities

### PR DESCRIPTION
**Pull request by R0LA1mRifcF8yAkk**

### CODE REVIEW

**Comment by R0LA1mRifcF8yAkk** [comment]
any hope getting this merged soon?

**Comment by R0LA1mRifcF8yAkk** [comment]
hello?

**Comment by AndyOGo** [comment]
@R0LA1mRifcF8yAkk 
If you need a maintained and clean alternative with greater support, may you check this out:

https://github.com/AndyOGo/stylelint-declaration-strict-value

**Comment by R0LA1mRifcF8yAkk** [comment]
thanks, I'll check it out

**Pull request closed without merging**
