### PR TITLE
use peerDeps

### PR DESCRIPTION
**Pull request by nosovk**
fix for https://github.com/sh-waqar/stylelint-declaration-use-variable/issues/36

### CODE REVIEW

**Comment by dartess** [comment]
Hi! Thanks for pr!

But so far the request does not solve the problem: `stylelint` still saved in the package-lock. 

Вы должны вручную удалить зависимость `npm un stylelint`, then specify it as a `peer`.

**Comment by dartess** [comment]
It would also be nice to indicate the need to set the stylelint in the README. At least specify this in the installation line.

**Comment by AndyOGo** [comment]
@nosovk 
@dartess 
If you need a maintained and clean alternative with peerDeps and others correct plus greater support, may you check this out:

https://github.com/AndyOGo/stylelint-declaration-strict-value

**Comment by sh-waqar** [comment]
Should be resolved by #50. Please let me know if it does not resolve the issue.

**Pull request closed without merging**
